// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductosCRUD.Server.Models;

#nullable disable

namespace ProductosCRUD.Server.Migrations
{
    [DbContext(typeof(ProductosCRUDContext))]
    partial class ProductosCRUDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductosCRUD.Server.Models.Producto", b =>
                {
                    b.Property<int>("idActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idActividad"));

                    b.Property<decimal>("condicionTrabajoActividad")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("conocimientoActividad")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("grupoOcupacionalActividad")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("impactoActividad")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("nombreActividad")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("observacionActividad")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("ponderacionActividad")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("ponderacionNivelActividad")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("relacionamientoActividad")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("responsabilidadActividad")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("idActividad");

                    b.HasIndex("nombreActividad")
                        .IsUnique();

                    b.ToTable("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
